defaults: &defaults
  bucket: <%= ENV['AMAZON_BUCKET'] %>
  access_key_id: <%= ENV['AMAZON_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AMAZON_SECRET_ACCESS_KEY'] %>

development:
  <<: *defaults

test:
  bucket: bucket-test
  access_key_id: xxx
  secret_access_key: xxx

production:
  <<: *defaults
